language: go
dist: xenial

go:
  - 1.11.x

cache:
  directories:
    # see https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-use-dep-in-ci
    - $GOPATH/pkg/dep

before_install:
  - mkdir -p $TRAVIS_HOME/.local/bin

install:
  - make install
  - make deps

script:
  - make cfn-test
  - make build
